- hosts: localhost
  # become: yes
  # become_method: sudo

  tasks:
  - name: Set git user.email
    community.general.git_config:
        name: user.email
        scope: global
        value: "DarthPjotr@users.noreply.github.com"

  - name: Set git user.name
    community.general.git_config:
        name: user.name
        scope: global
        value: "DarthPjotr"

  - name: Set git credential.helper
    community.general.git_config:
        name: credential.helper
        scope: global
        value: "/mnt/c/Progra\\ Files/Git/mingw64/libexec/git-core/git-credential-manager-core.exe"


