- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
  # setup some config files
  - name: edit dnf.conf remove tsflags=nodocs
    ini_file: 
      path: /etc/dnf/dnf.conf 
      section: main
      option: tsflags
      state: absent
  - name: edit /etc/wsl.conf 
    ini_file: 
      path: /etc/wsl.conf 
      section: network
      option: generateHosts
      value: "false"
  # install packages
  - name: update all
    dnf:
      state: latest
      name: "*"
  - name: install ansible
    dnf:
      state: latest
      name:
      - ansible
      - ansible-collection-ansible-posix
  - name: install tools
    dnf:
      state: latest
      name:
      # - wslu
      - less
      - procps-ng
      - wget 
      - curl 
      - sudo 
      - ncurses 
      - dnf-plugins-core 
      - dnf-utils 
      - passwd 
      - findutils 
  - name: install network tools
    dnf:
      state: latest
      name: 
      - iputils
      - traceroute
      - bind-utils
      - iproute
      - telnet
  - name: install container tools
    dnf:
      state: latest
      name:
      - podman
      - podman-plugins
      - buildah
      - skopeo
  - name: install man
    dnf:
      state: latest
      name: 
      - man-pages 
      - man-db 
      - man
  - name: install vim
    dnf:
      state: latest
      name:
      - vim-enhanced
      - vim-powerline
  - name: install shell enhancements
    dnf:
      state: latest
      name:
      - powerline
      - powerline-fonts
      - bash-completion
  - name: install git
    dnf:
      state: latest
      name:
      - git

  # reinstall shadow-utils
  - name: reinstall shadow-utils
    command: dnf reinstall shadow-utils -y
    # dnf:
    #   state: latest
    #   name:
    #   - shadow-utils 

  # enable ping
  - name: set  net.ipv4.ping_group_range="0 2000"
    ansible.posix.sysctl:
      name: net.ipv4.ping_group_range
      value: "0 2000"
      state: present
      sysctl_file: yes

  # edit podman configuration
  - name: edit container.conf so systemd is not needed
    ini_file: 
      path: /usr/share/containers/containers.conf
      section: engine
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { option: cgroup_manager, value: '"cgroupsfs"' }
      - { option: events_logger, value: '"file"' } 
      # events_logger = "file"
